version: "3.8"

services:
  db:
    image: postgres:15.3-bookworm
    env_file:
      - backend/.docker.env
    container_name: shared_finances-postgres
    restart: unless-stopped
    volumes:
      - postgresdb_data_container:/data/db
    ports:
      - 5432:5432
    networks:
      - database
  api:
    container_name: shared_finances-api
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    networks:
      - api
      - database
    depends_on:
      - db
    env_file:
      - backend/.docker.env
  nginx:
    container_name: shared_finances-nginx
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    networks:
      - api
      - front
    depends_on:
      - api
    ports:
      - 80:80
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    env_file:
      - .env

networks:
  api:
    internal: true
  database:
  front:

volumes:
  postgresdb_data_container: