version: "3.8"

services:
  db:
    image: mongo:4.0.26-xenial
    container_name: shared_finances-mongo
    restart: always
    command: "--bind_ip_all --replSet rs0"
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - 27017:27017
    networks:
      - database
  db_replica_configure:
    image: mongo:4.0.26-xenial
    entrypoint:
      - /mongodb/initiate_replica.sh
    volumes:
      - mongodb_data_container:/data/db
      - ./mongodb:/mongodb
    networks:
      - database
    depends_on:
      - db
  api:
    container_name: shared_finances-api
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      - api
      - database
    depends_on:
      - db
    environment:
      - DB_URL=mongodb://shared_finances-mongo
  angular:
    container_name: shared_finances-angular
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    networks:
      - api
      - front
    depends_on:
      - api
    ports:
      - 80:80

networks:
  api:
    internal: true
  database:
    internal: true
  front:

volumes:
  mongodb_data_container:
  credentials: