server:
    servlet:
        contextPath: /api
    logging:
        enabled: false
    port: ${PORT}
    error:
        include-message: always

spring:
    data:
        web:
            pageable:
                max-page-size: 100
                default-page-size: 40
    jpa:
        show-sql: true
        open-in-view: false
        database-platform: org.hibernate.dialect.MySQL8Dialect
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                globally_quoted_identifiers: true
    datasource:
        url: jdbc:postgresql://${POSTGRES_CONNECTION_STRING}/${POSTGRES_DB}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
    quartz:
        job-store-type: jdbc
        jdbc:
            initialize-schema: always
        properties:
            org:
                quartz:
                    jobStore:
                        driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate


sf-app:
    job-timezone: ${JOB_TIMEZONE}
    expires-invite-after-min: 30
    expires-invite-cron: 0 0/30 * ? * * *
