server:
    servlet:
        contextPath: /api
    logging:
        enabled: false
    port: 8080
    error:
        include-message: always

spring:
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL8Dialect
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                globally_quoted_identifiers: true
    datasource:
        url: jdbc:postgresql://${POSTGRES_CONNECTION_STRING}/${POSTGRES_DB}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
