server:
  servlet:
      contextPath: /api
  logging:
    enabled: false
  port: 8080

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_CONNECTION_STRING}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  security:
    oauth2.resourceserver.jwt.jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com